#ifndef GUARD_CONSTANTS_HEAL_LOCATIONS_H
#define GUARD_CONSTANTS_HEAL_LOCATIONS_H



#define HEAL_LOCATION_LITTLEROOT_TOWN_BRENDANS_HOUSE_2F 1
#define HEAL_LOCATION_LITTLEROOT_TOWN_MAYS_HOUSE_2F 2
#define HEAL_LOCATION_PETALBURG_CITY 3
#define HEAL_LOCATION_SLATEPORT_CITY 4
#define HEAL_LOCATION_MAUVILLE_CITY 5
#define HEAL_LOCATION_RUSTBORO_CITY 6
#define HEAL_LOCATION_FORTREE_CITY 7
#define HEAL_LOCATION_LILYCOVE_CITY 8
#define HEAL_LOCATION_MOSSDEEP_CITY 9
#define HEAL_LOCATION_SOOTOPOLIS_CITY 10
#define HEAL_LOCATION_EVER_GRANDE_CITY 11
#define HEAL_LOCATION_LITTLEROOT_TOWN_BRENDANS_HOUSE 12
#define HEAL_LOCATION_LITTLEROOT_TOWN_MAYS_HOUSE 13
#define HEAL_LOCATION_OLDALE_TOWN 14
#define HEAL_LOCATION_DEWFORD_TOWN 15
#define HEAL_LOCATION_LAVARIDGE_TOWN 16
#define HEAL_LOCATION_FALLARBOR_TOWN 17
#define HEAL_LOCATION_VERDANTURF_TOWN 18
#define HEAL_LOCATION_PACIFIDLOG_TOWN 19
#define HEAL_LOCATION_EVER_GRANDE_CITY_POKEMON_LEAGUE 20
#define HEAL_LOCATION_SOUTHERN_ISLAND_EXTERIOR 21
#define HEAL_LOCATION_BATTLE_FRONTIER_OUTSIDE_EAST 22


/*
#define HEAL_LOCATION_FROSTDEW_TOWN		1
#define HEAL_LOCATION_RIMEROSE_CITY		2	
#define HEAL_LOCATION_HINTERLEAF_CITY		3
#define HEAL_LOCATION_MARIBUD_TOWN		4	
#define HEAL_LOCATION_SEASPROUT_TOWN		5
#define HEAL_LOCATION_CRAGSTEN_CITY		6	
#define HEAL_LOCATION_VALLEROOT_TOWN		7
#define HEAL_LOCATION_METROLUX_CITY		8	
#define HEAL_LOCATION_DRAFTVINE_CITY		9
#define HEAL_LOCATION_AVALORN_TOWN		10	
#define HEAL_LOCATION_HARTHPEAK_CITY		11
#define HEAL_LOCATION_HARTHPEAK2_CITY		12

#define HEAL_LOCATION_MT_CHILLSPIRE		13
#define HEAL_LOCATION_ROUTE_1			14
#define HEAL_LOCATION_ROUTE_2			15
#define HEAL_LOCATION_ROUTE_3			16
#define HEAL_LOCATION_ROUTE_4			17
#define HEAL_LOCATION_ROUTE_5			18
#define HEAL_LOCATION_ROUTE_6			19
#define HEAL_LOCATION_ROUTE_7			20
#define HEAL_LOCATION_ROUTE_8			21
#define HEAL_LOCATION_ROUTE_9			22
#define HEAL_LOCATION_ROUTE_10			23
#define HEAL_LOCATION_ROUTE_11			24
#define HEAL_LOCATION_ROUTE_12			25
#define HEAL_LOCATION_ROUTE_13			26
#define HEAL_LOCATION_ROUTE_14			27
#define HEAL_LOCATION_ROUTE_15			28
#define HEAL_LOCATION_ROUTE_16			29
#define HEAL_LOCATION_ROUTE_17			30

#define HEAL_LOCATION_WILD_AREA_BADLANDS	31
#define HEAL_LOCATION_WILD_AREA_MOUNTAINS	32
#define HEAL_LOCATION_WILD_AREA_MARSH		33
#define HEAL_LOCATION_WILD_AREA_FOREST		34
*/


#endif // GUARD_CONSTANTS_HEAL_LOCATIONS_H
